# Generated by Django 5.0.7 on 2026-03-27 06:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('participant_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('browser', models.CharField(blank=True, max_length=100)),
                ('os', models.CharField(blank=True, max_length=100)),
                ('screen_width', models.PositiveIntegerField(blank=True, null=True)),
                ('screen_height', models.PositiveIntegerField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('variant_assigned', models.CharField(blank=True, max_length=100)),
                ('consent_screen_recording', models.BooleanField(default=False)),
                ('consent_camera', models.BooleanField(default=False)),
                ('consent_audio', models.BooleanField(default=False)),
                ('consent_given_at', models.DateTimeField(blank=True, null=True)),
                ('current_block_index', models.PositiveIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('dropped_off_at_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoffs', to='studies.block')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='studies.study')),
            ],
            options={
                'db_table': 'participant_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordingChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recording_type', models.CharField(choices=[('screen', 'Screen'), ('camera', 'Camera'), ('audio', 'Audio')], max_length=20)),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(upload_to='recordings/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studies.block')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_chunks', to='participants.participantsession')),
            ],
            options={
                'db_table': 'recording_chunks',
                'ordering': ['chunk_index'],
            },
        ),
        migrations.CreateModel(
            name='HeatmapEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('click', 'Click'), ('tap', 'Tap'), ('scroll', 'Scroll'), ('mousemove', 'Mouse Move'), ('rage_click', 'Rage Click')], max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('scroll_y', models.FloatField(blank=True, null=True)),
                ('element_selector', models.CharField(blank=True, max_length=500)),
                ('element_text', models.CharField(blank=True, max_length=255)),
                ('timestamp_offset', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_events', to='studies.block')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap_events', to='participants.participantsession')),
            ],
            options={
                'db_table': 'heatmap_events',
                'indexes': [models.Index(fields=['session', 'block'], name='heatmap_eve_session_49f7d3_idx'), models.Index(fields=['block', 'event_type'], name='heatmap_eve_block_i_a5ccbd_idx')],
            },
        ),
        migrations.CreateModel(
            name='BlockResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_completed', models.BooleanField(blank=True, null=True)),
                ('task_completion_status', models.CharField(blank=True, choices=[('success', 'Success'), ('fail', 'Fail'), ('skip', 'Skip')], max_length=20)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_spent_seconds', models.PositiveIntegerField(default=0)),
                ('recording_url', models.URLField(blank=True)),
                ('recording_start_offset', models.FloatField(blank=True, null=True)),
                ('recording_end_offset', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='studies.block')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='participants.participantsession')),
            ],
            options={
                'db_table': 'block_responses',
                'ordering': ['created_at'],
                'unique_together': {('session', 'block')},
            },
        ),
    ]
